version: '3'
services:
  
  backend:
    image: flask
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: myDb

 volumes:
  mysql-data:     
    
  
